---
title: "Run HMSC for plants with traits"
output: word_document
date: "2023-04-03"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Model inputs :

```{r, echo=FALSE}
library(magrittr)
library(Hmsc)
library(ggplot2)


load("../ASICS_code/cro/models/with_traits_and_phylo/S2_fit_models_thin_1000_samples_250_chains_4.Rdata")
models_cro <- models
Y_cro <- models_cro$`presence-absence model`$Y %>% head
XData_cro <- models_cro$`presence-absence model`$XData
XFormula_cro <- models_cro$`presence-absence model`$XFormula
TrData_cro <- models_cro$`presence-absence model`$TrData
TrFormula_cro <- models_cro$`presence-absence model`$TrFormula
phyloTree_cro <- models_cro$`presence-absence model`$phyloTree


load("../ASICS_code/ker/models/with_traits/S2_fit_models_thin_1000_samples_250_chains_4.Rdata")
models_ker <- models
Y_ker <- models_ker$`presence-absence model`$Y %>% head
XData_ker <- models_ker$`presence-absence model`$XData
XFormula_ker <- models_ker$`presence-absence model`$XFormula
TrData_ker <- models_ker$`presence-absence model`$TrData
TrFormula_ker <- models_ker$`presence-absence model`$TrFormula
phyloTree_ker <- models_ker$`presence-absence model`$phyloTree

```


# Crozet
```{r}
colnames(Y_cro)
TrData_cro
ape::plot.phylo(phyloTree_cro)

```


# Kerguelen
```{r}
colnames(Y_ker)
TrData_ker
ape::plot.phylo(phyloTree_ker)

```

```{r, eval=FALSE}
# model structure:
m = Hmsc(Y=Y, XData = XData,  XFormula = XFormula,
         TrData = TrData, TrFormula = TrFormula,
         phyloTree = phylo_cro,
         distr="probit",
         studyDesign = studyDesign, ranLevels=list(site=rL.site, id=rL.id))

```


Variance partition for Crozet
```{r, echo=FALSE}

# fetch data stored in models
m_cro  <- models_cro[[1]]
covariates = attr(terms(m_cro$XFormula),"term.labels")
# 1940 sites * 11 species * 1000 samples
preds = computePredictedValues(m_cro)
VP = computeVariancePartitioning(m_cro)
vals = VP$vals
mycols = viridis::viridis(nrow(VP$vals))
MF = evaluateModelFit(hM=m_cro, predY=preds)
R2 = NULL

# plot settings      
theme_set(theme_bw())

# ggplot format
varpart <- VP$vals %>%
  as.data.frame 
varpart$covariates <- rownames(varpart)
varpart %<>% 
  tidyr::pivot_longer(!covariates, names_to = "species", values_to = "var_partition")
varpart$covariates <- factor(varpart$covariates, 
                             levels = rev(c("mean_temp","accum_prec","pente",
                                            "exposition","Random: site" ,"Random: id")))

# plot variance partitioning for Crozet
varpart %>%
  ggplot(aes(fill=covariates, y = var_partition, x= species)) + 
  geom_bar(position = "stack", stat="identity") +
  viridis::scale_fill_viridis(discrete=T) + 
  ggtitle("Crozet") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```


Variance partition for Kerguelen
```{r, echo=FALSE}

# fetch data stored in models
m_ker  <- models_ker[[1]]
covariates = attr(terms(m_ker$XFormula),"term.labels")
# 1940 sites * 11 species * 1000 samples
preds = computePredictedValues(m_ker)
VP = computeVariancePartitioning(m_ker)
vals = VP$vals
mycols = viridis::viridis(nrow(VP$vals))
MF = evaluateModelFit(hM=m_ker, predY=preds)
R2 = NULL

# plot settings      
theme_set(theme_bw())

# ggplot format
varpart <- VP$vals %>%
  as.data.frame 
varpart$covariates <- rownames(varpart)
varpart %<>% 
  tidyr::pivot_longer(!covariates, names_to = "species", values_to = "var_partition")
varpart$covariates <- factor(varpart$covariates, 
                             levels = rev(c("mean_temp","accum_prec","pente",
                                            "exposition","Random: site" ,"Random: id")))

# plot variance partitioning for Crozet
varpart %>%
  ggplot(aes(fill=covariates, y = var_partition, x= species)) + 
  geom_bar(position = "stack", stat="identity") +
  viridis::scale_fill_viridis(discrete=T) + 
  ggtitle("Kerguelen") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```

```{r, echo=FALSE}
support.level.beta = NULL #Default: 0.95
support.level.gamma = NULL #Default: 0.95
support.level.omega = NULL #Default: 0.9
var.part.order.explained = NULL #Default: in variance partitioning of explained variance, species are shown in the order they are in the model
var.part.order.raw = NULL #Default: in variance partitioning of raw variance, species are shown in the order they are in the model
show.sp.names.beta = NULL #Default: species names shown in beta plot if there are at most 30 species and no phylogeny
plotTree = NULL #Default: tree is plotted in Beta plot if the model includes it
omega.order = NULL #Default: species shown in the order they are in the model
show.sp.names.omega = NULL #Default: species names shown in beta plot if there are at most 30 species


if(is.null(support.level.beta)) support.level.beta = 0.95
if(is.null(support.level.gamma)) support.level.gamma =  0.95
if(is.null(support.level.omega)) support.level.omega =  0.9

```


Make map of Crozet based on beta predicted values

```{r}
crozet = TRUE
cro <- sf::st_read("../data/SIG/Contours/CRO_contours.shp")

source("../ASICS_code/process_occurrences.R")
pred_cro <- predict(m_cro)
map_cro <- cbind(env_vars[models_cro[[1]]$XData$id, ], pred_cro)




Epred_cro <- Reduce("+",pred_cro)/length(pred_cro)
dim(Epred_cro)
head(Epred_cro, 10)

# merge with coordinates from the sites that we kept in the analysis:

Epred_cro <- cbind(Epred_cro, cro_sites_xy[rownames(Epred_cro), c("latitude", "longitude")])

Epred_cro %<>% st_as_sf(coords = c("longitude", "latitude" ), crs = 4326)

Epred_cro %>%
  ggplot() +
  geom_sf( aes(color = `Acaena magellanica`)) 


# merge with coords:
cro_com_mat <- cbind(cro_com_mat, cro_sites_xy[rownames(cro_com_mat) %in% cro_sites_xy$numero_observation, c("latitude", "longitude")]) %>%
  st_as_sf(coords = c("longitude", "latitude" ), crs = 4326)

# extract plants of interest:
A_magellanica <- cro_com_mat %>%
  dplyr::filter(`Acaena magellanica` >0) %>%
  dplyr::select(`Acaena magellanica`, geometry)

# plot presences:
A_magellanica %>%
  ggplot() +
  geom_sf(data=cro) +
  geom_sf( ) 


```


Same for Kerguelen


```{r}

crozet = FALSE
source("../ASICS_code/process_occurrences.R")
ker <- sf::st_read("../data/SIG/Contours/KER_contours.shp")
m_ker <- models_ker[[1]]

# get predicted values : this is a list of length = 1000 ( 4 chains of 250 samples) 
pred_ker <- predict(m_ker)
dim(pred_ker[[1]])

# these are still presence/absences. To estimate probabilities, we take the 
# means --> posterior mean predictions

Epred_ker <- Reduce("+",pred_ker)/length(pred_ker)
dim(Epred_ker)
head(Epred_ker, 10)

# merge with coordinates from the sites that we kept in the analysis:

Epred_ker <- cbind(Epred_ker, ker_sites_xy[rownames(Epred_ker), c("latitude", "longitude")]) %>%
  as.data.frame
#Epred_ker <- Epred_ker[-which(is.na(Epred_ker$longitude)), ]
Epred_ker %<>% st_as_sf(coords = c("longitude", "latitude" ), crs = 4326)
Epred_ker %>%
  ggplot() +
  geom_sf( aes(color = `Acaena magellanica`)) 

# compare with the presence only:
# merge with coords:
ker_com_mat <- cbind(ker_com_mat, ker_sites_xy[rownames(ker_com_mat) %in% ker_sites_xy$numero_observation, c("latitude", "longitude")]) %>%
  st_as_sf(coords = c("longitude", "latitude" ), crs = 4326)

# extract plants of interest:
A_magellanica <- ker_com_mat %>%
  dplyr::filter(`Acaena magellanica` >0) %>%
  dplyr::select(`Acaena magellanica`, geometry)

# plot presences:
A_magellanica %>%
  ggplot() +
  geom_sf(data=ker) +
  geom_sf( )



```
